[colors.primary]
background = "#0e0e0e"
foreground = "#ffffff"

[colors.cursor]
cursor = "#107C10"
text = "#0e0e0e"

[colors.selection]
background = "#107C10"
text = "#0e0e0e"

[colors.normal]
black = "#0e0e0e"
red = "#D04242"
green = "#3CDB4E"
yellow = "#ECDB33"
blue = "#40CCD0"
magenta = "#9b59b6"
cyan = "#40CCD0"
white = "#ffffff"

[colors.bright]
black = "#444444"
red = "#e74c3c"
green = "#4ade80"
yellow = "#fef08a"
blue = "#67e8f9"
magenta = "#c084fc"
cyan = "#67e8f9"
white = "#ffffff"
